spring:
  rabbitmq:
    host: "${spring.rabbitmq.host}"
    port: "${spring.rabbitmq.port}"
    username: "${spring.rabbitmq.username}"
    password: "${spring.rabbitmq.password}"
  application:
    name: openAiApi
  config:
    import: optional:file:.env[.properties]


proxy:
  api:
    key: ${proxy.api.key}


server:
  port: 8081