spring:
  rabbitmq:
    host: "${spring.rabbitmq.host}"
    port: "${spring.rabbitmq.port}"
    username: "${spring.rabbitmq.username}"
    password: "${spring.rabbitmq.password}"
  application:
    name: WeatherApi
  config:
    import: optional:file:.env[.properties]

weather:
  api:
    key: "${weather.api.key}"

server:
  port: 8084