spring:
  rabbitmq:
    host: "${spring.rabbitmq.host}"
    port: "${spring.rabbitmq.port}"
    username: "${spring.rabbitmq.username}"
    password: "${spring.rabbitmq.password}"

  application:
    name: foodApi

  config:
    import: optional:file:.env[.properties]


server:
  port: 8086

food:
  api:
    key: ${food.api.key}

